add_rules("mode.debug", "mode.release")

add_includedirs("./lua")
add_includedirs("./src")
add_includedirs("./src/base_object")
add_includedirs("./src/user_object")
add_includedirs("./to_code")

target("lua-cad")
    set_kind("binary")
    add_files("to_code/*.c")
    add_files("lua/*.c|onelua.c|lua.c")
    add_files("src/*.c|lua-cad.c")
    add_files("src/base_object/*.c")
    add_files("src/user_object/*.c")
target_end()
